#+OPTIONS: toc:nil
#+OPTIONS: H:2
#+BEGIN_abstract
This is my abstract, it is a really good abstract
#+END_abstract
\newpage
\newcounter{savepage}
\thispagestyle{empty}

#+LATEX_HEADER: \input{lat_pre.tex}
#+LATEX: \setlength\parindent{0pt}
#+LATEX_HEADER: \usepackage[square]{natbib}
\tableofcontents
# \thispagestyle{empty}




bibliographystyle:agsm
\newpage
\pagenumbering{Roman}
#+LATEX: \listoffigures
\newpage
#+LATEX: \listoftables
\newpage
\printnoidxglossary[sort=letter, title = Abbreviations]

\newpage


\cleardoublepage
\setcounter{savepage}{\arabic{page}}
\pagenumbering{arabic}

* Introduction
\label{sec:intro}





*** Data
    The data used for the purpose of the optimization and the backtesting is the adjusted closing price from the Apple Stock from 12th December 1980 to the
    28th December 2018. The data was downloaded from Yahoo Finance using the /quantmod/ module from the R statistical programming language.
    The data was split in two parts. The first part of the data, which spans from 12th December 1980 to 28th December of 1989 was used to optimize the parameter for
    the \gls{dcs}, which will be further elaborated in section \ref{sec:strategy}. The other part was used for the actual backtesting of the strategy and the analysis
    thereof. Also it was used for the backtest and analysis of the results for the \gls{bah} strategy, which will be discussed in the following section.

	 \begin{figure}[H]
		 \centering
		 \caption{Apple Stock Chart - from December 1980 to December 2018}
		 \label{img:stock}
		 \includegraphics[width = 10cm]{stock}
	 \end{figure}


* Strategies
\label{sec:strategy}.
** Buy and Hold
   \label{sec:buyhold}

   The first strategy that will be examined here is the \gls{bah} strategy. The \gls{bah} strategy does what its name suggests. At the beginning of the
   period the asset will be bought and hold over the entire observed period. A graphical representation of the strategy applied to the Apple Stock from
   1990-01-01 to 2018-12-01 can be seen in figure \ref{img:buyhold-strategy}.
   This strategy also serves as the reference strategy against which the \gls{dcs} in chapter \ref{sec:donchian} is measured.
   If the \gls{bah} strategy fares better in terms of the calmar ratio than Donchian Channel strategy, one would be better off just buying the stock and
   do not try to outperform its performance.



** Donchian Channel Strategy
   \label{sec:donchian}

Technical Trading strategies are usually based off of some quantitative indicator, which generates the respective buy or sell signals.
In this paper, the Donchian Channel has been chosen to demonstrate a typical quantitative strategy.
The Donchian Channel has been invented by Richard Donchian in the 1970's and received a wider recognition after the Turtle Traders (see Appendix X)
 publicized their use of it. The system presented in this paper can be classified as breakout system, since it generates a buy signal whenever
the closing price is greater than the upper bound of the Donchian Channel and a short signal is triggered whenever the asset has a closing price
below the lower bound.


*** Indicator
  The indicator chosen for the backtest is called the **Donchian Channel**. It was invented by Richard Donchian in the 1970's and falls under the category of trend following indicators. It was used with great success by Richard Dennis
  who used it to train the Turtle Traders (**enter reference here**). Particularly its simplicity makes it a good candidate for backtesting since it is really easy to compute and thus makes it not computationally expensive.
  The indicator consists in its simplest form of an upper bound and a lower bound. The upper bound consists of the highest price of the last /n/ days, whereas the lower bound consists of the lowest price of the last /n/ days.
  The more complex indicator also consists of a middle line, which is simply an average of the aforementioned upper and lower bounds. However, in this paper it was not used and is therefore not mentioned in the following mathematical
  representation of the indicator.



  \begin{align}
  Upper \;Channel\; = Maximum(p_{1}, p_{2}, ..., p_{n}) \\
  Lower \;Channel\; = Minimumimum(p_{1}, p_{2}, ..., p_{n})
  \end{align}

*** Strategy
 While it is possible to use the Donchian Channel as a counter trend strategy, the following trend following strategy was used for the purpose of this paper:
 A long signal is triggered, whenever the closing price of the current period lies above the upper bound and a short signal is generated whenever the closing price of the current period falls below the lower bound. Although plenty
 of possible signals to exit the positions exist, in this paper a sell signal exits a long trade and a short signal exits a long trade.
 The whole backtest (optimization and trading) was implemented in R using the quantstrat package. The code that generated the following results can be found in the Appendix.


** Calmar Ratio
\label{sec:calmar}
   To compare the above stated strategies in a reasonable way, it is advisable to pick a statistic that does not solely rely on the profits generated by the
   specific strategy, but also takes their risk into account.
   Therefore a measure to quantify the relation of risk and return is needed. In this paper, the statistic employed for a fair comparison of the
   aforementioned attributes is the Calmar Ration. The Calmar ratio takes the profit generated by a strategy in relation to the maximum drawdown it
   generates. Thus showing the relationship between these two in an easily comparable value. A mathematical representation of the Calmar Ratio
   can be seen in equation \eqref{eq:calmar-ratio}.

\begin{equation}
	 \label{eq:calmar-ratio}
   Calmar\;Ratio = \frac{Profit}{Maximumimum\;Drawdown}
\end{equation}
* Results
  
** Buy and Hold Strategy
\label{sec:bah-results}

As can be seen in the second chart of figure \ref{img:buyhold-strategy}, the \gls{bah} strategy entered the first transaction in mid 1990
and exited this position at 28.12.2018. This is due to the fact, that the \gls{bah} strategy only consists of two trades.
One long position to enter the market and its corresponding sell order. 
The upper chart of figure \ref{img:buyhold-strategy} shows the price of the asset during the course of the backtest
It is noticeable the Apple stock did not move much until about 2005 when a long lasting uptrend began.
This uptrend went on through the 2000s and 2010s until in late 2018, when it suddenly reversed and the Apple stock began to decline sharply,
which continued throughout the rest of the observed period. \\



The lower chart of figure \ref{img:buyhold-performance} depicts the drawdowns of the \gls{bah} strategy. It can be seen that 
the strategy exhibits three major drawdowns during the backtest. The first severe drawdown occurred during the year 2012, where
Apples stock price had the first major decline since its uptrend started in 2005. However, Apples stock price began to recover 
in 2013 and regained its former price level at around the beginning of 2014. 
The next major drawdown occurred at the end of 2015 and lasted throughout the year of 2016 and ended in early 2017.

The most severe drawdown took place in late 2018. This drawdown wiped out much of the
gains that were accumulated through the last two years. The \gls{bah} strategy lost close to $200000, in just a few weeks.
This drawdown seems to mark a turning point for the Apple stock, indicating that its long lasting uptrend is finally over.


	\begin{figure}[H]
		\centering
		\caption{Buy \& Hold Strategy}
		\label{img:buyhold-strategy}
		\includegraphics[width = 10cm]{buyhold_trading}
	\end{figure}


Figure \ref{img:buyhold-performance} depicts in the upper chart the cumulative return of this strategy over the observed time period.
It can be seen, that just like the cumulative \gls{pl} in figure \ref{img:buyhold-strategy}, the cumulative return was basically
flat during the 1990s and the early 2000s. However, beginning with the aforementioned uptrend the cumulative return of the stock
also began to increase dramatically.

The middle chart of figure \ref{img:buyhold-performance} shows the daily returns of this strategy. Again, the fact that the 
stock did not exhibit any large price in- or decreases in the period of 1990 until about 2005 can also be seen here. 
In contrast to the period of 2005 - 2018 the daily returns of the asset are miniscule, whereas the daily returns in later periods
are quite erratic which also displays that the volatility of the daily returns was increasing sharply. \\

By looking at the lower chart, which depicts the drawdowns of the strategy, it can be seen that the strategy exhibited
multiple drawdowns during the course of this backtest. The most severe ones took place in the years of 2008, 2012 through
2013, 2015 through much of 2016 and the last and most extreme one at the end of 2018.

During the course of the drawdown starting in 2008 the Apple stock lost about 30% of its value and only regained its loss 
in early 2010. At the time of next drawdown, which was even more severe, it lost about 60% which is about the same percentage loss,
that occurred during the next drawdown in 2005.
However, the most intense drawdown of 2018 eradicated close to 90% of the returns the stock gained in the previous periods.



	\begin{figure}[H]
		\centering
		\caption{Buy \& Hold Performance}
		\label{img:buyhold-performance}
		\includegraphics[width = 10cm]{buyhold_performance}
	\end{figure}



Nonetheless, a closer look at the data this strategy generated is needed to assess its overall performance.
Table \ref{tab:bah-stats} shows the trading statistics of it.
It can be seen that some of the statistics are missing, and most of the statistics show the same value.
This is due to the fact, that by its nature, the \gls{bah} strategy only consists of two trades and therefore 
some of the statistics (e.g. the standard deviation of the trade \gls{pl}) need more data than is available for
their calculation. This also explains why a lot of the values are the same. Since there is only one trade 
(a buy and a sell order) were executed, the median and the average \gls{pl} are necessarily the same.


\begin{table}[!Htbp] \centering 
\caption{Buy & Hold Strategy - Trading Statistics}
\label{tab:bah-stats}
\begin{tabular}{@{\extracolsep{5pt}} cc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & AAPL \\ 
\hline \\[-1.8ex] 
Portfolio & buyHold \\ 
Symbol & AAPL \\ 
Number of Transactions & 2 \\ 
Number of Trades & 1 \\ 
Net Trading PL & 3093171 \\ 
Average Trade PL & 3093171 \\ 
Median Trade PL & 3093171 \\ 
Largest Winner & 3093171 \\ 
Largest Loser & 0 \\ 
Gross Profits & 3093171 \\ 
Gross Losses & 0 \\ 
Standard Deviation Trade PL &  \\ 
Standard Err Trade PL &  \\ 
Percent Positive & 100 \\ 
Percent Negative & 0 \\ 
Profit Factor &  \\ 
Average Winning Trade & 3093171 \\ 
Median Winning Trade & 3093171 \\ 
Average Losing Trade &  \\ 
Median Losing Trade &  \\ 
Average Daily PL & 3093171 \\ 
Median Daily PL & 3093171 \\ 
Standard Deviation Daily PL &  \\ 
Standard Err Daily PL &  \\ 
Annual Sharpe Ratio &  \\ 
Maximum Drawdown & -1704800 \\ 
Calmar Ratio & 1.814389 \\ 
Average WinLoss Ratio &  \\ 
Median WinLoss Ratio &  \\ 
Maximum Equity & 4609972 \\ 
Minimum Equity & -22187.5 \\ 
End Equity & 3093171 \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table} 


It can be seen that the strategy netted a profit of $3093171, which corresponds to a total return of 309.31%. 
However, one has to take to account the amount of risk the strategy exhibited to assess its viability. 
The maximum drawdown of this strategy was $1704800, which is less than the profits generated but still substantial.
But with these two numbers, the calculation of the *Calmar Ratio* becomes possible. As stated in section \ref{sec:calmar},
this is the statistic used to compare the presented strategies and to determine which one is to be favored.

The calmar ratio of the \gls{bah} strategy is 1.814389 which means that the strategy generated about 1.8 times 
more profits than it lost in its maximum drawdown. This is the value against which the \gls{dcs} will be compared with.


** Donchian Channel Strategy
\label{sec:dcs-results}

In contrast to the \gls{bah} strategy, the \gls{dcs} strategy executed multiple trades during the tested time span.
This becomes evident by looking at the upper two charts of figure \ref{img:donchian-strategy}. In the upper chart,
a green arrow indicates the opening of a long position, while the red arrows indicate that a short trade was executed.
The lower chart of these two, shows the dollar amount of each position opened. Since a maximum position size of $20000
was set for this backtest, the strategy only went long or short the aforementioned amount at any given point in time. \\



	\begin{figure}[H]
		\centering
		\caption{Donchian Channel Strategy}
		\label{img:donchian-strategy}
		\includegraphics[width = 10cm]{strategy_trading}
	\end{figure}

Like before in section \ref{sec:bah-results}, the lower charts display the cumulative \gls{pl} and the drawdowns, respectively.
It can be seen, that the strategy was overall successful judged by the curve showing the cumulative \gls{pl}.
Also it becomes apparent, that the strategy did not exhibit very severe drawdowns, at least corresponding to the dollar
value of the portfolio. \\


However, figure \ref{img:donchian-performance} paints another picture. The cumulative returns in the upper chart
are rising at a steep angle from 2005 on onward. This is hardly surprising, since the \gls{dcs} strategy is a 
trend-following strategy and therefore fares well in a trending environment. But is also becomes apparent, that 
the cumulative returns are pretty volatile, which is reinforced by looking at the second chart in figure \ref{img:donchian-performance}.
Like before in section \ref{sec:bah-results}, this chart shows the daily returns of the strategy in detail. 
It can be seen clearly, that the returns also became more volatile with the continuation of the trend and reach
their highest volatility at the end of 2018.

Also, the lower chart which presents the percentage values of the drawdowns the strategy encountered paint a more
dismal picture than the monetary drawdowns shown in \ref{img:donchian-strategy}. It can be seen, that the strategy
encountered frequently drawdowns of over 20% and in some cases even over 40%. Further, there were two instances 
in which the drawdown was even as severe as 50% or over. Again, the period in late 2018 sticks out. It can be seen
that this drawdown was close to 80% which makes it the most extreme drawdown encountered during the period of 
backtesting this strategy.


	\begin{figure}[H]
		\centering
		\caption{Donchian Channel Strategy - Performance}
		\label{img:donchian-performance}
		\includegraphics[width = 10cm]{strategy_performance}
	\end{figure}

Table \ref{tab:strategy-stats} shows the statistics the \gls{dcs} strategy generated in detail. It executed 
67 transactions, consisting of 33 trades. The odd number can be explained by the fact that the last order the strategy
carried out was still open at the end of the backtesting period and therefore no opposing order to close the position
was initiated. \\

Further it can be seen that the strategy generated a net profit of $4178491 which corresponds to a total return of
417.8491%. The largest winning trade of the strategy yielded a profit of $1224190 and the largest losing trade yielded 
a negative $138581.5. Also the strategy yielded an amount of $4045903 in gross profits and a total of -$278411.5 in
gross losses. The table also shows that a percentage of 42.42% of all trades resulted in profit while the percentage 
of losses amounts to 57.58%. Taking the aforementioned statistics into account this result shows that while the strategy
had more losing than winning trades, the overall amount of winning trades were larger than the overall losses encountered
during the backtest.


\begin{table}[!htbp] \centering 
\caption{Donchian Channel Strategy - Trading Statistics}
\label{tab:strategy-stats}
\begin{tabular}{@{\extracolsep{5pt}} cc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & AAPL \\ 
\hline \\[-1.8ex] 
Portfolio & donchian-channel \\ 
Symbol & AAPL \\ 
Number of Transactions & 67 \\ 
Number of Trades & 33 \\ 
Net Trading PL & 4178491 \\ 
Average Trade PL & 114166.4 \\ 
Median Trade PL & -2063.58 \\ 
Largest Winner & 1224190 \\ 
Largest Loser & -138581.5 \\ 
Gross Profits & 4045903 \\ 
Gross Losses & -278411.5 \\ 
Standard Deviation Trade PL & 299234.9 \\ 
Standard Err Trade PL & 52090.11 \\ 
Percent Positive & 42.42424 \\ 
Percent Negative & 57.57576 \\ 
Profit Factor & 14.53209 \\ 
Average Winning Trade & 288993 \\ 
Median Winning Trade & 123304.2 \\ 
Average Losing Trade & -14653.24 \\ 
Median Losing Trade & -6617.14 \\ 
Average Daily PL & 114166.4 \\ 
Median Daily PL & -2063.58 \\ 
Standard Deviation Daily PL & 299234.9 \\ 
Standard Err Daily PL & 52090.11 \\ 
Annual Sharpe Ratio & 6.056564 \\ 
Maximum Drawdown & -1266610 \\ 
Calmar Ratio & 3.298955 \\ 
Average WinLoss Ratio & 19.72213 \\ 
Median WinLoss Ratio & 18.63407 \\ 
Maximum Equity & 4873301 \\ 
Minimum Equity & -81340.76 \\ 
End Equity & 4178491 \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table} 


But also, just as in section \ref{sec:buyhold-results} one has to take into account the risk associated with the 
strategy. The metric already presented for this purpose is the maximum drawdown which was a negative $1266610.  
This means that the strategy exhibited a calmar ratio of 3.298955 which means that the \gls{dcs} generated roundabout
3.3 times the amount of profit than it took on in risk, represented by the the net profit and the maximum drawdown 
respectively.

** Buy & Hold vs Donchian Channel Strategy
\label{sec:comparison}
*** Relative Performance


	\begin{figure}[H]
		\centering
		\caption{Relative Performance}
		\label{img:relative-performance}
		\includegraphics[width = 10cm]{relative_performance}
	\end{figure}

*** Equity Curves


	\begin{figure}[H]
		\centering
		\caption{Donchian Channel Strategy vs Buy \& Hold - Equity Curves}
		\label{img:donchian-vs-buyhold}
		\includegraphics[width = 10cm]{strategy_vs_market}
	\end{figure}

*** Performance Table

\begin{table}[!htbp] \centering 
  \caption{Donchian Channel Strategy vs Buy & Hold - Trade Statistics} 
  \label{tab:both-tradestats} 
\begin{tabular}{@{\extracolsep{5pt}} ccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & AAPL & AAPL.1 \\ 
\hline \\[-1.8ex] 
Portfolio & donchian-channel & buyHold \\ 
Symbol & AAPL & AAPL \\ 
Number of Transactions & 67 & 2 \\ 
Number of Trades & 33 & 1 \\ 
Net Trading PL & 4178491 & 3093171 \\ 
Average Trade PL & 114166.4 & 3093171 \\ 
Median Trade PL & -2063.58 & 3093171 \\ 
Largest Winner & 1224190 & 3093171 \\ 
Largest Loser & -138581.5 & 0 \\ 
Gross Profits & 4045903 & 3093171 \\ 
Gross Losses & -278411.5 & 0 \\ 
Standard Deviation Trade PL & 299234.9 &  \\ 
Standard Err Trade PL & 52090.11 &  \\ 
Percent Positive & 42.42424 & 100 \\ 
Percent Negative & 57.57576 & 0 \\ 
Profit Factor & 14.53209 &  \\ 
Average Winning Trade & 288993 & 3093171 \\ 
Median Winning Trade & 123304.2 & 3093171 \\ 
Average Losing Trade & -14653.24 &  \\ 
Median Losing Trade & -6617.14 &  \\ 
Average Daily PL & 114166.4 & 3093171 \\ 
Median Daily PL & -2063.58 & 3093171 \\ 
Standard Deviation Daily PL & 299234.9 &  \\ 
Standard Err Daily PL & 52090.11 &  \\ 
Annual Sharpe Ratio & 6.056564 &  \\ 
Maximum Drawdown & -1266610 & -1704800 \\ 
Calmar Ratio & 3.298955 & 1.814389 \\ 
Average WinLoss Ratio & 19.72213 &  \\ 
Median WinLoss Ratio & 18.63407 &  \\ 
Maximum Equity & 4873301 & 4609972 \\ 
Minimum Equity & -81340.76 & -22187.5 \\ 
End Equity & 4178491 & 3093171 \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table} 

*** Fama-French 3 Factor Model
    

Table \ref{tab:regression} shows the output of the regression of the excess returns ($gross\; returns - risk\; free\; rate$ ) against the three Fama-French Factors.
The factor delineated as /MktRf/ in the regression output is the market return adjusted by the risk free rate. This factor shows the \gls{dcs} returns sensitivity to the 
markets excess returns.  

\begin{table}[!htbp] \centering 
  \caption{Fama French 3 Factor Regression} 
  \label{tab:regression} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & excess\_returns \\ 
\hline \\[-1.8ex] 
 MktRf & 0.001$^{***}$ \\ 
  & (0.0002) \\ 
  & \\ 
 SMB & 0.001$^{***}$ \\ 
  & (0.0004) \\ 
  & \\ 
 HL & $-$0.002$^{***}$ \\ 
  & (0.0004) \\ 
  & \\ 
 Constant & $-$0.010$^{***}$ \\ 
  & (0.0003) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 7,306 \\ 
R$^{2}$ & 0.010 \\ 
Adjusted R$^{2}$ & 0.009 \\ 
Residual Standard  Error & 0.022 (df = 7302) \\ 
F Statistic & 24.088$^{***}$ (df = 3; 7302) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table} 


* Conclusion

#+LaTeX: \begin{appendices}
\newpage

bibliography:references.bib

\newpage
* Appendix
#+NAME: Optimization Script
**  Script for Optimization
#+BEGIN_SRC R

if (!require("quantstrat")) {
    if(!require("devtools")) {
        install.packages("devtools")
        require(devtools)
    }
    install_github("braverock/blotter") # dependency
    install_github("braverock/quantstrat")
}

install.packages("quantmod")

library(quantstrat)
library(quantmod)


currency("USD")

# set up the financial asset used and the dates

initDate <- "1980-01-01"
startDate <- "1980-01-01"
endDate <- "1989-12-31"

getSymbols("AAPL", from = startDate, to = endDate)#, from = startDate, to = endDate, adjusted = TRUE)
stock("AAPL", currency="USD", multiplier = 1)
AAPL <- na.omit(AAPL)
# Set up initial equity and transaction costs
start_equity <- 1e6
orderSize <- start_equity * 0.02
fee = -10 # Transaction fee of $2
stopp_loss <- 0.02

init_n <- 20
n_opt_range <- 1:100


Sys.setenv(TZ="UTC")


donchian_strategy <- "donchian-channel"

# set up the strategy and portfolio components
rm.strat(donchian_strategy)

strategy(donchian_strategy, store = TRUE)
initPortf(donchian_strategy, "AAPL", initDate = initDate)
initAcct(donchian_strategy,  portfolios = donchian_strategy,
         initDate = initDate, initEq = start_equity,
         currency = 'USD')

initOrders(donchian_strategy, initDate = initDate)


# Create the indicator
add.indicator(strategy = donchian_strategy,
              name = "DonchianChannel",
              arguments = list(HL = quote(HLC(mktdata)[, 1:2]),
                               n = init_n,
                               include.lag = TRUE
                               ),
              label = "DNC")

#---- Set up the signals ----#
add.signal(donchian_strategy, name = "sigComparison",
           arguments = list(
               columns = c("Close", "high.DNC"),
               relationship = "gt"),
           label = "long" )

add.signal(donchian_strategy, name = "sigComparison",
           arguments = list(
               columns = c("Close", "low.DNC"),
               relationship = "lt"),
           label = "short" )


#---- Set up the Rules ---- #

# Enter Long
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = "long",
             sigval = TRUE,
             orderside = "long",
             ordertype = "market",
             replace = FALSE,
             TxnFees = fee,
             orderqty = +orderSize),
         type = "enter",
         label = "EnterLong",
         )

# Enter short
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = "short",
             sigval = TRUE,
             orderside = "short",
             ordertype = "market",
             TxnFees = fee,
             replace = FALSE,
             orderqty = -orderSize),
         type = "enter",
         label = "EnterShort"
         )


# Exit Long
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = 'short',
             sigval = TRUE,
             orderqty = 'all',
             ordertype = 'market',
             replace = TRUE,
             TxnFees = fee,
             orderside = 'long'),
         type = 'exit'
         )

# Exit Short
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = 'long',
             sigval = TRUE,
             orderqty = 'all',
             ordertype = 'market',
             replace = TRUE,
             TxnFees = fee,
             orderside = 'short'),
         type = 'exit'
         )

#results <- applyStrategy(donchian_strategy, portfolios = donchian_strategy)
## getTransactions(Portfolio=donchian_strategy, Symbol=symbols)
## chart.Posn(donchian_strategy, Symbol = symbols, Dates = "2017::")

## updatePortf(donchian_strategy)
## updateAcct(donchian_strategy)
## updateEndEq(donchian_strategy)
## chart.Posn(donchian_strategy, Symbol = 'AAPL', Dates = '2005::')

## trade_stats <- perTradeStats(donchian_strategy,symbols)


# Optimize the moving average parameter

add.distribution(donchian_strategy,
                 paramset.label = 'DonchianChannel',
                 component.type = 'indicator',
                 component.label = 'DNC',
                 variable = list(n = n_opt_range),
                 label = 'days_opt')
library(parallel)
detectCores()

if( Sys.info()['sysname'] == "Windows" )
{
    library(doParallel)
    registerDoParallel(cores=detectCores())
} else {
    library(doMC)
    registerDoMC(cores=detectCores())
}



optimization <- apply.paramset(donchian_strategy,
                               paramset.label='DonchianChannel',
                               portfolio.st=donchian_strategy,
                               account.st=donchian_strategy, nsamples=0)

tradeResults <- optimization$tradeStats
idx <- order(tradeResults[,1], tradeResults[,2])
tradeResults <- tradeResults[idx,]

max_calmar_parameter <- which.max(tradeResults$Calmar Ratio)
max_calmar_parameter


#+END_SRC


#+NAME: Optimization Script
**  Script for Backtesting & Analysis
#+BEGIN_SRC R

# ----- IMPORTANT -----
# Please set the working directory to the current directory using setwd()
# before running the script

# parameter 11

# Setup cpde taken from
if (!require("quantstrat")) {
    if(!require("devtools")) {
        install.packages("devtools")
        require(devtools)
    }
    install_github("braverock/blotter") # dependency
    install_github("braverock/quantstrat")
}

## install.packages("lattice")
## install.packages("quantmod")
## install.packages("xts")
## install.packages("xtable")
## install.packages("lubridate")
## install.packages("fBasics")

library(quantstrat)
library(lattice)
library(quantmod)
library(xts)
library(xtable)
library(lubridate)
library(fBasics)
options(scipen=999)

options(repr.plot.width = 6, repr.plot.height = 4)
currency("USD")

# set up the financial asset and the dates

initDate <- "1990-01-01"
startDate <- "1990-01-01"
endDate <- "2018-12-31"

getSymbols("AAPL", from = startDate, to = endDate)
AAPL <- na.omit(AAPL)
colnames(AAPL) <- c('Open', 'High', 'Low', 'Close', 'Volume', 'Adjusted')

# Set up initial equity and transaction costs
start_equity <- 1e6
orderSize <- start_equity * 0.02
fee = -10 # Transaction fee of $2
stopp_loss <- 0.02

options(repr.plot.width = 6, repr.plot.height = 4)
init_n <- 11


Sys.setenv(TZ="UTC")


donchian_strategy <- "donchian-channel"
rm.strat(donchian_strategy)

stock("AAPL", currency="USD", multiplier = 1)
strategy(donchian_strategy, store = TRUE)
initPortf(donchian_strategy, "AAPL", initDate = initDate)
initAcct(donchian_strategy,  portfolios = donchian_strategy,
         initDate = initDate, initEq = start_equity,
         currency = 'USD')

initOrders(donchian_strategy, initDate = initDate)


# Create the indicator
add.indicator(strategy = donchian_strategy,
              name = "DonchianChannel",
              arguments = list(HL = quote(HLC(mktdata)[, 1:2]),
                               n = init_n,
                               include.lag = TRUE
                               ),
              label = "DNC")

#---- Set up the signals ----#
add.signal(donchian_strategy, name = "sigComparison",
           arguments = list(
               columns = c("Close", "high.DNC"),
               relationship = "gt"),
           label = "long" )

add.signal(donchian_strategy, name = "sigComparison",
           arguments = list(
               columns = c("Close", "low.DNC"),
               relationship = "lt"),
           label = "short" )


#---- Set up the Rules ---- #

# Enter Long
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = "long",
             sigval = TRUE,
             orderside = "long",
             ordertype = "market",
             replace = FALSE,
             TxnFees = fee,
             orderqty = +orderSize),
         type = "enter",
         label = "EnterLong",
         )

# Enter short
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = "short",
             sigval = TRUE,
             orderside = "short",
             ordertype = "market",
             replace = FALSE,
             TxnFees = fee,
             orderqty = -orderSize),
         type = "enter",
         label = "EnterShort"
         )


# Exit Long
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = 'short',
             sigval = TRUE,
             orderqty = 'all',
             ordertype = 'market',
             replace = TRUE,
             TxnFees = fee,
             orderside = 'long'),
         type = 'exit'
         )

# Exit Short
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = 'long',
             sigval = TRUE,
             orderqty = 'all',
             ordertype = 'market',
             replace = TRUE,
             TxnFees = fee,
             orderside = 'short'),
         type = 'exit'
         )

results <- applyStrategy(donchian_strategy, portfolios = donchian_strategy)
getTransactions(Portfolio=donchian_strategy, Symbol="AAPL")

updatePortf(donchian_strategy)
updateAcct(donchian_strategy)
updateEndEq(donchian_strategy)
chart.Posn(donchian_strategy, Symbol = 'AAPL', Dates = '2016::')
#chart.Posn(donchian_strategy, Symbol = 'AAPL', Dates = '2000::2010')

trade_stats <- perTradeStats(donchian_strategy,"AAPL")

tstats = t(tradeStats(donchian_strategy, 'AAPL'))
xtable(tstats)

mk <- mktdata['1990-01-01::2018-12-31']
mk.df <- data.frame(Date=time(mk),coredata(mk))
mk.df

rets <- PortfReturns(donchian_strategy)
rownames(rets) <- NULL
charts.PerformanceSummary(rets/100, colorset=bluefocus)

######## buy and hold test
#the code for this this part was taken from
# tim trice book of quantstrat
#https://timtrice.github.io/


rm.strat("buyHold")

initPortf("buyHold", symbols = "AAPL", initDate = initDate)
initAcct('buyHold', portfolios = 'buyHold', initDate = initDate,
         initEq = start_equity)

CurrentDate <- time(getTransactions(Portfolio = donchian_strategy,
                            Symbol = "AAPL"))[2]
equity = getEndEq("buyHold", CurrentDate)
ClosePrice <- as.numeric(Cl(AAPL[CurrentDate,]))
addTxn("buyHold", Symbol = "AAPL",
       TxnDate = CurrentDate, TxnPrice = ClosePrice,
       TxnQty = orderSize, TxnFees = 0)

LastDate <- last(time(AAPL))
LastPrice <- as.numeric(Cl(AAPL[LastDate,]))
addTxn("buyHold", Symbol = "AAPL",
       TxnDate = LastDate, TxnPrice = LastPrice,
       TxnQty = -orderSize, TxnFees = 0)

updatePortf(Portfolio = "buyHold")
updateAcct(name = "buyHold")
updateEndEq(Account = "buyHold")
chart.Posn("buyHold", Symbol = "AAPL")

tstats_buyhold = t(tradeStats('buyHold', 'AAPL'))
tstats_buyhold
xtable(tstats_buyhold)

#Performance Summary
returns = PortfReturns(donchian_strategy)
colnames(returns) = 'Dochian Strategy'
returns <- returns/100
charts.PerformanceSummary(returns/100, colorset = 'darkblue')
#
return_buyhold <- PortfReturns(Account = "buyHold")
colnames(return_buyhold) = 'Buy and Hold'
return_buyhold <- return_buyhold/100
charts.PerformanceSummary(return_buyhold, colorset='darkblue')
#
return_both = cbind(returns, return_buyhold)
charts.PerformanceSummary(return_both, geometric = FALSE,
                           wealth.index = TRUE,
                           main = 'Donchian Channel Strategy vs Market')
#
#
buyhold_per_trade_stats <- t(perTradeStats('buyHold',"AAPL"))
buyhold_per_trade_stats

# Total returns over the observed time perios
buyhold_total_return <- (as.numeric(tstats_buyhold[length(tstats_buyhold)]) / start_equity) * 100
buyhold_total_return
strategy_total_return <- (as.numeric(tstats[length(tstats)]) / start_equity) * 100
strategy_total_return

times_market <- as.numeric(tstats[length(tstats)]) / as.numeric(tstats_buyhold[length(tstats_buyhold)])
times_market

#---- Relative Performance -----
chart.RelativePerformance(returns, return_buyhold,
                          colorset = c("red", "blue"), lwd = 2,
                          legend.loc = "topleft")

#---- Fama French 3 Factor Model ----
ff_factors <- read.csv2("./ff_factors.csv", sep = ',')

# change the columns to the correct data type
ff_factors$Mkt.RF <- as.numeric(as.character(ff_factors$Mkt.RF))
ff_factors$SMB <- as.numeric(as.character(ff_factors$SMB))
ff_factors$HML <- as.numeric(as.character(ff_factors$HML))
ff_factors$RF <- as.numeric(as.character(ff_factors$RF))

# Convert the first column to a date format
colnames(ff_factors)[1] <- "Date"
ff_factors$Date <-  ymd(ff_factors$Date)
ff_date <- ff_factors$Date
ff_factors <- ff_factors[, -1]

# Rename the columns
colnames(ff_factors) <- c("MktRf", "SMB", "HL", "RF")

# Create an XTS Object
ff_factors <- xts(ff_factors, ff_date)
ff_factors <- ff_factors["1990/20181228"]
ff_factors <- ff_factors/100

excess_returns = PortfReturns(donchian_strategy) - ff_factors$RF
# FF 3 Factor Model
model <- lm(excess_returns ~ MktRf + SMB + HL, data=ff_factors)
summary(model)
xtable(model, digits = c(0, 11, 11, 4, 4))

# Portfolio Summary Graphs
strategy_pf <- getPortfolio(donchian_strategy)
xyplot(strategy_pf$summary, type = "h", col = 4)

buyhold_pf <- getPortfolio("buyHold")
xyplot(buyhold_pf$summary, type = "h", col = 4)

# Summary statistics of Buy & Hold strategy
buyhold_summary <- basicStats(return_buyhold * 100)
xtable(buyhold_summary, digits = c(0, 5))


# Summary statistics of the Donchian Channel strategy
strategy_summary <- basicStats(returns * 100)
xtable(strategy_summary, digits = c(0, 5))

# Tstats table for both
tstats_table_both <- cbind(tstats, tstats_buyhold)
xtable(tstats_table_both)

# Chart the whole series
initDate <- "1980-01-01"
startDate <- "1980-01-01"
endDate <- "2018-12-31"

getSymbols("AAPL", from = startDate, to = endDate)
AAPL <- na.omit(AAPL)
colnames(AAPL) <- c('Open', 'High', 'Low', 'Close', 'Volume', 'Adjusted')
                                        # Chart the Series
chartSeries(AAPL, theme = 'white')
#+END_SRC

#+RESULTS:

# \printbibliography
