#+OPTIONS: toc:nil
#+BEGIN_abstract
\thispagestyle{empty}
\noindent
In this paper the profitability and the risk employed of a quantitative trading strategy will be examined and
compared to the Buy & Hold strategy proposed by the /Efficient Market Hypothesis/. The quantitative trading
strategy used for this purpose will be based on the Donchian Channel. The metrics used for the purpose of the
comparison will be the calmar ratio, which takes the net profit generated by a strategy in relation to the
maximum drawdown it exhibited. Further, a regression on the three Fama-French factors is done to reveal if
the strategy is exposed to any of these factors.
It was found that the quantitative strategy exhibits a higher calmar ration than the Buy & Hold strategy, it did
in fact generate a negative alpha. Therefore the strategy cannot be claimed superior.
#+END_abstract
\newpage
\newcounter{savepage}
\thispagestyle{empty}

#+LATEX_HEADER: \input{lat_pre.tex}
#+LATEX: \setlength\parindent{0pt}
#+LATEX_HEADER: \usepackage[square]{natbib}
\tableofcontents
# \thispagestyle{empty}




 bibliographystyle:agsm
 # bibliographystyle:dinat
\newpage
\pagenumbering{Roman}
#+LATEX: \listoffigures
\newpage
#+LATEX: \listoftables
\newpage
\printnoidxglossary[sort=letter, title = Abbreviations]

\newpage


\cleardoublepage
# \setcounter{savepage}{\arabic{page}}
\pagenumbering{arabic}

* Introduction
\label{sec:intro}
In this paper the viability of a quantitative trading strategy will be examined and compared to the \gls{bah} strategy
proposed by the \gls{emh} (citealt:fama_efficient_1970). If this strategy is able to outperform, the \gls{bah} strategy it can be seen as superior and
the \gls{emh} can be considered refuted.

For this purpose, the statistical computing language /R/ in conjunction with the /quantstrat/ package was used.
The test was done using the backtesting methodology, where a specific quantitative trading strategy was tested on the
price of the Apple stock during period of January 1980 until December 2018. The chart for this period can be seen in figure \ref{img:stock}.
The data was split into two parts for the following reasons.
The first part of the data set, which spans from January 1980 to December 1989, was used as a training set for the strategy.
This part has been used to optimize the parameter the quantitative strategy takes into account to derive its trading signals.
The second data set employed in this paper was used to actually trade the strategy and to examine its result.
This data set spans from January 1990 to December 2018.

The \gls{emh} hypothesis states, that all information about a stock gets immediately discounted into the price, making
it impossible to outperform the practice of buying and holding the asset (commonly known as the \gls{bah} strategy),
without taking any additional risk. This means, that the price of an asset always trades at its fair value (cf citealt:fama_efficient_1970).

Quantitative traders (also called /technical traders/) on the other hand, do not believe the \gls{emh} to be true and
try to aim at a higher performance than the market itself provides. Their reasoning for this belief is characterized by
the following three main assumptions they make about the markets.

The first assumption states that markets move in trends, which means that markets are always in one of three states.
The first state is called an uptrend which means that a period of rising prices is followed by a period of even higher
prices. The second state on the other hand is called a downtrend).

The second assumption, which is shared by both proponents of the \gls{emh} and by technical traders, is that 
all information about the asset is already discounted in the price. But in contrary to the \gls{emh} quantitative
traders derive a different conclusion from this assumption. According to them, this just means that there is no
need to incorporate any fundamental information into account, since this is already reflected by the price.

Their third an last assumption is that markets do not change over time, therefore prices form repetitive patterns
which can be exploited to gain excess returns (cf citealt:murphy_technical_1999).

	 \begin{figure}[H]
		 \centering
		 \caption{Apple Stock Chart - from December 1980 to December 2018}
		 \label{img:stock}
		 \includegraphics[width = 10cm]{stock}
	 \end{figure}

Another reason why quantitative trading strategies can be successful is due to behavioural factors.
When prices move upwards for a considerable amount of time, investors may get greedy and, in accordance to
the first assumption of quantitative traders, the market forms an uptrend. The same mechanism can be observed
in the other market direction, in case of extreme fear.

This behavioural aspect is stated by Pring as follows:
\begin{quote}
\textit{"The technical approach to investment is essentially a reflection of the idea that prices move in trends
which are determined by the changing attitudes of investors to ward a variety of economic, monetary, political
in psychological forces...Since the technical approach is based on the theory that price is a reflection of
mass psychology ("the crowd") in action, it attempts to forecast future price movements on the assumption that
crowd psychology moves between panic, fear, and pessimism one hand and confidence, excessive optimism, and
greed on the other hand."} (see \citep[pp.~ 2-3]{Pring2002})
\end{quote}

Before continuing with the topic at hand, it is advisable to describe what a quantitative trading strategy actually
is and how it is employed.
Quantitative trading strategies are based off of some indicator, which is usually some mathematical formula that takes
the price as an input and derives ,based on its calculation, the optimal points in time for buying and selling a security.
According to these signals the asset will be traded accordingly.

However, there are actually two classes of indicators available which both trade the market in a very different way.
The first kind of indicator is a trend following indicator, which does what its name suggests. The indicator
tries to identify the current trend and gives a buy signal in an uptrend and vice versa in a downtrend.
The second kind of indicator is a counter trend indicator. These indicators aim to give a buy signal whenever
an earlier downtrend is in the process of reversing and will give a sell signal whenever a previous uptrend reverses.
Notwithstanding, this class of indicators is beyond the scope of this paper and will not be examined further.

Based on these indicators, buy and sell signals will be given and traded accordingly.

An example of a trend-following strategy is the SMA Crossover Strategy. It consists of two \gls{sma}s, each taking a
different time horizon into account. A buy signal is given whenever the "faster" (meaning
the \gls{sma} which takes a shorter period of time into account than the other) crosses the "slower" \gls{sma} from below.
The signal to sell the asset is given whenever the fast \gls{sma} crosses the slow \gls{sma} from above.
This strategy can be seen in figure \ref{img:sma_example}, where the strategy is used
on the Apple stock. In this example the fast \gls{sma} takes 10 days of price data into account and is shown in
this graph by the red line. The slow \gls{sma} on the other hand, takes 20 days of price data into account and is
represented by the blue line. \\
\noindendt

This indicator will not be used in this paper and therefore no mathematical representation of it is needed, but
it still serves as good example of how a quantitative trading strategy can be derived. \\
\noindendt

During the last decades, a lot of studies have been published concerning the viability of technical trading systems.
Despite being viewed with suspicion by the academic community, some research actually shows that they
can be applied successfully. A study by conducted Brock, Lakonishok and LeBaron, published in the /Journal of Finance/
demonstrated that it is possible to generate above average returns using quantitative trading strategies (cf citealt:Brock1992).
Another study conducted by Mitchell & Ratner examined the profitability of a quantitative trading strategy
in ten emerging markets. While they found that in only two out of these countries their strategy was profitable,
they also reported that in most cases it correctly predicted the direction of changes in the return series (cf citealt:RATNER19991887).

	 \begin{figure}[H]
		 \centering
		 \caption{SMA Example}
		 \label{img:sma_example}
		 \includegraphics[width = 10cm]{sma_example}
	 \end{figure}


    Contrary to the study of Brock, Lakonishok and LeBaron, Hudson, Dempsey & Keasy could not replicate their
    results on the UK Stock market during the years of 1935 until 1994. They found that while the same technical
    trading rules have some predictive value, it is not possible to generate above average returns due to the
    fact of high trading costs.
    Another early study conducted by Fama & Blume also found no evidence of the superiority of quantitative trading
    strategies over the \gls{bah} strategy (cf citealt:FamaBlume1966), which is consistent with the findings of
    Famas \gls{emh}.
    \newpage
* Methodology
\label{sec:methodology}
** Strategies
*** Buy and Hold
    \label{sec:buyhold}

 The first strategy used in this paper is the so called \gls{bah} strategy. This strategy will also serve as a benchmark,
 against which the quantitative trading strategy observed in this paper will be measured. The \gls{bah} strategy works exactly
 like its name suggests. The asset will be bought at the beginning of the period and will be sold at the end of it.
 For a better comparison the quantitative strategy, the \gls{bah} strategy will enter the market at the same time as
 its quantitative counterpart. Therefore a fair comparison over the same time frame is made possible. 

 As already stated, this strategy also is at the heart of Fama and Frenchs \gls{emh}. If the quantitative strategy is not able to beat
 the \gls{bah} strategy, the \gls{emh} cannot be disproved.

*** Donchian Channel Strategy
    \label{sec:donchian}

 The quantitative strategy used in this paper for the purpose of backtesting, the \gls{dcs} was used.
 The \gls{dcs} can be classified as a trend following strategy and is based on the *Donchian Channel*, which was
 invented by Richard Donchian in the 1970's (cf citealt:murphy_technical_1999). 

 The Donchian Channel (in this paper) consists of two channels which serve as the signals lines for the strategy.
 These channels can be calculated according to equation \eqref{eq:donchian-channel}. It can be seen, that their
 calculation is quite simple. The upper channel is just the highest closing price of the last n days, while
 the lower channel consists of  the lowest price of the last /n/ days. 

 \begin{equation}
\begin{split}
   \label{eq:donchian-channel}
   Upper \;Channel\; = Max(p_{1}, p_{2}, ..., p_{n}) \\
   Lower \;Channel\; = Min(p_{1}, p_{2}, ..., p_{n})
\end{split}
   \end{equation}

 The \gls{dcs} generates a long signal whenever the current price lies above the upper channel of the strategy and
 accordingly, a short signal whenever the current price lies below the lower channel. It becomes apparent that the
 time frame over which the two channels are calculated is an important factor, since one obtains different values
 for them according the number of for this parameter /n/. 

 To solve this issue, the price data from 1980 to 1990 was used to optimize this parameter. As stated in the introduction, this was done using
 the statistical programming language R in conjunction with the quantstrat package. This optimization yielded a value
 of 95 days as the optimal number of days to maximize the results of strategy over the time period of 1990 until 2018.
 The script used for this purpose can be found in appendix \ref{sec:opt}. 

** Methods for Comparison
*** Calmar Ratio
 \label{sec:calmar}
    To compare the above stated strategies in a reasonable way, it is advisable to pick a statistic that does not solely rely on the profits generated by the
    specific strategy, but also takes into account the risk they take on.
    Therefore a measure to quantify the relation of risk and return is needed. In this paper, the statistic employed for such a comparison of the
    aforementioned attributes is the *Calmar Ratio*. The Calmar ratio takes the profit generated by a strategy in relation to the maximum drawdown it
    generates. Thus showing the relationship between these two in an easily comparable manner. A mathematical representation of the Calmar Ratio
    can be seen in equation \eqref{eq:calmar-ratio}.

 \begin{equation}
	  \label{eq:calmar-ratio}
    Calmar\;Ratio = \frac{Profit}{Maximumimum\;Drawdown}
 \end{equation}

    If the calmar ratio of the \gls{dcs} is higher than the one the \gls{bah} strategy produced, then it can be deemed as superior.
    This is because this result shows that the quantitative trading strategy generated a higher return with lower risk. 

    Nonetheless, to really estimate if the strategy can be seen as less risky, it is advisable to look for risks that cannot be found solely by
    conducting a backtest. One such method is the Fama-French Three Factor model, which will be introduced in the following
    section. 

*** Fama French Model
\label{sec:ff-intro}

    The Fama-French three factor model has been developed by Eugene Fama and Kenneth french and was published in their
    seminal paper "Common Risk Factors in the Returns on Stocks and Bonds" in 1970. 

    They showed that markets are generally efficient, but proved the existence of two additional factors (next to
    the excess market returns) which positively identify reasons for possible excess returns of a given strategy.
    According to French and Fama these factors are additional risk factors, and the higher return of these stocks can be attributed to those risks.
    Since the excess market returns is also considered in this model it is generally called the Fama-French three Factor Model. 

    As already mentioned, the first factor considered by the model is the excess market return. This risk factor
    consists of the market return adjusted for the risk free rate. This is done, to show the markets return without taking into account
    the safe risk free component and can be therefore seen as the /"pure"/ market return. 

    The next factor that positively influences the performance of a stock is its market capitalization. They found
    that stocks with a smaller market capitalization tend to outperform stocks with a bigger capitalization the market on a consistent basis.
    However, this also poses some additional risk, since stocks with small market capitalization are usually companies that are just starting out or
    are older companies who have not been that successful so far. 

    The third and therefore last risk factor that Fama and French found to be of significance, was the price-to-book
    factor. They showed empirical evidence, that stocks with a low price to book value also outperform the market by
    a significant margin. A low price to book value means in practice, that the stock is trading below
    the stated book value of their balance sheets. In theory the market capitalization of a company should be at least
    equal to the book value estimated by accountants, otherwise it would be possible to buy the whole company at this lower
    market price and then sell all its assets at the stated book value thus generating a profit (cf citealt:fama_common_1993). 

    If the \gls{dcs} is not exposed to these three factors and does generate a significant alpha, it is safe to conclude
    that the strategy is superior to the \gls{bah} strategy proposed by Fama and French. Otherwise, the opposite holds
    true.

* Results

** Buy and Hold Strategy
\label{sec:bah-results}

As can be seen in the second chart of figure \ref{img:buyhold-strategy}, the \gls{bah} strategy entered the first transaction in mid 1990
and exited this position at 28.12.2018. This is due to the fact, that the \gls{bah} strategy only consists of two trades.
One long position to enter the market and its corresponding sell order.
The upper chart of figure \ref{img:buyhold-strategy} shows the price of the asset during the course of the backtest.
It is noticeable that the Apple stock did not move much until about 2005 when a long lasting uptrend began.
This uptrend went on through the 2000s and 2010s until in late 2018, when it suddenly reversed and the Apple stock began to decline sharply,
which continued throughout the rest of the observed period. 

The lower chart of figure \ref{img:buyhold-performance} depicts the drawdowns of the \gls{bah} strategy. It can be seen that
the strategy exhibits three major drawdowns during the backtest. The first severe drawdown occurred during the year 2012, where
Apples stock price had the first major decline since its uptrend started in 2005. However, Apples stock price began to recover
in 2013 and regained its former price level at around the beginning of 2014.
The next major drawdown occurred at the end of 2015 and lasted throughout the year of 2016 and ended in early 2017. 

The most severe drawdown took place in late 2018. This drawdown wiped out much of the
gains that were accumulated through the last two years. The \gls{bah} strategy lost close to $200000, in just a few weeks.
This drawdown seems to mark a turning point for the Apple stock, indicating that its long lasting uptrend is finally over.

	\begin{figure}[H]
		\centering
		\caption{Buy \& Hold Strategy}
		\label{img:buyhold-strategy}
		\includegraphics[width = 10cm]{buyhold_trading}
	\end{figure}

Figure \ref{img:buyhold-performance} depicts the cumulative returns of this strategy in the upper chart.
It can be seen, that just like the cumulative \gls{pl} in figure \ref{img:buyhold-strategy}, the cumulative return was basically
flat during the 1990s and the early 2000s. However, beginning with the aforementioned uptrend, the cumulative returns of the stock
also began to increase dramatically. 

The middle chart of figure \ref{img:buyhold-performance} shows the daily returns of this strategy. Again, the fact that the
stock did not exhibit any large price in- or decreases in the period of 1990 until about 2005 can also be seen here.
In contrast to the period of 2005 - 2018 the daily returns of the asset are miniscule, whereas the daily returns in later periods
are quite erratic which also displays that the volatility of the daily returns increased sharply. 

By looking at the lower chart, which depicts the drawdowns of the strategy, it can be seen that the strategy exhibited
multiple drawdowns during the course of this backtest. The most severe ones took place in the years of 2008, 2012 through
2013, 2015 through much of 2016 and the last and most extreme one at the end of 2018. 

During the course of the drawdown starting in 2008 the Apple stock lost about 30% of its value and only regained its loss
in early 2010. At the time of next drawdown, which was even more severe, it lost about 60% which is about the same percentage loss,
that occurred during the next drawdown in 2005.
However, the most intense drawdown of 2018 eradicated close to 90% of the returns the stock gained in the previous periods.

	\begin{figure}[H]
		\centering
		\caption{Buy \& Hold Performance}
		\label{img:buyhold-performance}
		\includegraphics[width = 10cm]{buyhold_performance}
	\end{figure}

Nonetheless, a closer look at the data this strategy generated is needed to assess its overall performance.
Table \ref{tab:bah-stats} shows its trading statistics.
It becomes visible that some of the statistics are missing, and most of the statistics show the same value.
This is due to the fact, that by its nature, the \gls{bah} strategy only consists of two trades and therefore
some of the statistics (e.g. the standard deviation of the trade \gls{pl}) need more data than is available for
their calculation. This also explains why a lot of the values are the same. Since there is only one trade
(a buy and a sell order) were executed, the median and the average \gls{pl} are necessarily the same.

\FloatBarrier
\begin{table}[!Htbp] \centering
\caption{Buy & Hold Strategy - Trading Statistics}
\label{tab:bah-stats}
\begin{tabular}{@{\extracolsep{5pt}} cc}
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & AAPL \\
\hline \\[-1.8ex]
Portfolio & buyHold \\
Symbol & AAPL \\
Number of Transactions & 2 \\
Number of Trades & 1 \\
Net Trading PL & 3093171 \\
Average Trade PL & 3093171 \\
Median Trade PL & 3093171 \\
Largest Winner & 3093171 \\
Largest Loser & 0 \\
Gross Profits & 3093171 \\
Gross Losses & 0 \\
Standard Deviation Trade PL &  \\
Standard Err Trade PL &  \\
Percent Positive & 100 \\
Percent Negative & 0 \\
Profit Factor &  \\
Average Winning Trade & 3093171 \\
Median Winning Trade & 3093171 \\
Average Losing Trade &  \\
Median Losing Trade &  \\
Average Daily PL & 3093171 \\
Median Daily PL & 3093171 \\
Standard Deviation Daily PL &  \\
Standard Err Daily PL &  \\
Annual Sharpe Ratio &  \\
Maximum Drawdown & -1704800 \\
Calmar Ratio & 1.814389 \\
Average WinLoss Ratio &  \\
Median WinLoss Ratio &  \\
Maximum Equity & 4609972 \\
Minimum Equity & -22187.5 \\
End Equity & 3093171 \\
\hline \\[-1.8ex]
\end{tabular}
\end{table}
\FloatBarrier

It can be seen that the strategy netted a profit of $3093171, which corresponds to a total return of 309.31%.
However, one has to take to account the amount of risk the strategy exhibited to assess its viability.
The maximum drawdown of this strategy was $1704800, which is less than the profits generated but still substantial.
But with these two numbers, the calculation of the *Calmar Ratio* becomes possible. As stated in section \ref{sec:calmar},
this is the statistic used to compare the presented strategies and to determine which one is to be favored. \\

The calmar ratio of the \gls{bah} strategy is 1.814389 which means that the strategy generated about 1.8 times
more profits than it lost in its maximum drawdown. This is the value against which the \gls{dcs} will be compared with.

** Donchian Channel Strategy
\label{sec:dcs-results}

In contrast to the \gls{bah} strategy, the \gls{dcs} strategy executed multiple trades during the tested time span.
This becomes evident by looking at the upper two charts of figure \ref{img:donchian-strategy}. In the upper chart,
a green arrow indicates the opening of a long position, while the red arrows indicate that a short trade was executed.
The lower chart of these two, shows the dollar amount of each position opened. Since a maximum position size of $20000
was set for this backtest, the strategy only went long or short the aforementioned amount at any given point in time. \\

Like before in section \ref{sec:bah-results}, the lower charts display the cumulative \gls{pl} and the drawdowns, respectively.
It can be seen, that the strategy was overall successful, judged by the curve showing the cumulative \gls{pl}.
Also it becomes apparent, that the strategy did not exhibit very severe drawdowns, at least corresponding to the dollar
value of the portfolio. 

However, figure \ref{img:donchian-performance} paints another picture. The cumulative returns in the upper chart
are rising at a steep angle from 2005 on onward. This is hardly surprising, since the \gls{dcs} strategy is a
trend-following strategy and therefore fares well in a trending environment. But is also becomes apparent, that
the cumulative returns are pretty volatile, which is reinforced by looking at the second chart in figure \ref{img:donchian-performance}.
Like before in section \ref{sec:bah-results}, this chart shows the daily returns of the strategy in detail.
It can be seen clearly, that the returns also became more volatile with the continuation of the trend and reach
their highest volatility at the end of 2018, when it was finally broken. 

Also, the lower chart which presents the percentage values of the drawdowns the strategy encountered paint a more
dismal picture than the monetary drawdowns shown in \ref{img:donchian-strategy}. It can be seen, that the strategy
encountered frequently drawdowns of over 20% and in some cases even over 40%. Further, there were two instances
in which the drawdown was even as severe as 50% or over. Again, the period in late 2018 sticks out. It can be seen
that this drawdown was close to 80% which makes it the most extreme drawdown encountered during the period of
backtesting this strategy. 

	\begin{figure}[H]
		\centering
		\caption{Donchian Channel Strategy}
		\label{img:donchian-strategy}
		\includegraphics[width = 10cm]{strategy_trading}
	\end{figure}



	\begin{figure}[H]
		\centering
		\caption{Donchian Channel Strategy - Performance}
		\label{img:donchian-performance}
		\includegraphics[width = 10cm]{strategy_performance}
	\end{figure}

Table \ref{tab:strategy-stats} shows the statistics the \gls{dcs} strategy generated in detail. It executed
67 transactions, consisting of 33 trades. The odd number can be explained by the fact that the last order the strategy
carried out was still open at the end of the backtesting period and therefore no opposing order to close the position
was initiated. 

Further it can be seen that the strategy generated a net profit of $4178491 which corresponds to a total return of
417.8491%. The largest winning trade of the strategy yielded a profit of $1224190 and the largest losing trade yielded
a negative $138581.5. Also the strategy yielded an amount of $4045903 in gross profits and a total of -$278411.5 in
gross losses. The table also shows that a percentage of 42.42% of all trades resulted in profit while the percentage
of losses amounts to 57.58%. Taking the aforementioned statistics into account this result shows that while the strategy
had more losing than winning trades, the overall amount of winning trades were larger than the overall losses encountered
during the backtest. \\

\FloatBarrier
\begin{table}[!htbp] \centering
\caption{Donchian Channel Strategy - Trading Statistics}
\label{tab:strategy-stats}
\begin{tabular}{@{\extracolsep{5pt}} cc}
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & AAPL \\
\hline \\[-1.8ex]
Portfolio & donchian-channel \\
Symbol & AAPL \\
Number of Transactions & 67 \\
Number of Trades & 33 \\
Net Trading PL & 4178491 \\
Average Trade PL & 114166.4 \\
Median Trade PL & -2063.58 \\
Largest Winner & 1224190 \\
Largest Loser & -138581.5 \\
Gross Profits & 4045903 \\
Gross Losses & -278411.5 \\
Standard Deviation Trade PL & 299234.9 \\
Standard Err Trade PL & 52090.11 \\
Percent Positive & 42.42424 \\
Percent Negative & 57.57576 \\
Profit Factor & 14.53209 \\
Average Winning Trade & 288993 \\
Median Winning Trade & 123304.2 \\
Average Losing Trade & -14653.24 \\
Median Losing Trade & -6617.14 \\
Average Daily PL & 114166.4 \\
Median Daily PL & -2063.58 \\
Standard Deviation Daily PL & 299234.9 \\
Standard Err Daily PL & 52090.11 \\
Annual Sharpe Ratio & 6.056564 \\
Maximum Drawdown & -1266610 \\
Calmar Ratio & 3.298955 \\
Average WinLoss Ratio & 19.72213 \\
Median WinLoss Ratio & 18.63407 \\
Maximum Equity & 4873301 \\
Minimum Equity & -81340.76 \\
End Equity & 4178491 \\
\hline \\[-1.8ex]
\end{tabular}
\end{table}
\FloatBarrier

But also, just as in section \ref{sec:bah-results} one has to take into account the risk associated with the
strategy. The metric already presented for this purpose is the maximum drawdown which was a negative $1266610.
This means that the strategy exhibited a calmar ratio of 3.298955 which means that the \gls{dcs} generated roundabout
3.3 times the amount of profit than it took on in risk, represented by the the net profit and the maximum drawdown
respectively. \\

** Buy & Hold vs Donchian Channel Strategy
\label{sec:comparison}

In this section the above stated characteristics and statistics of both strategies will be compared to asses if the
\gls{dcs} strategy is superior to the \gls{bah} strategy. For this purpose multiple ways are shown.
The first and most intuitive one is to show both equity curves of the strategies in one chart to get a first impression
of how the strategies fared against each other. This can be seen in the upper chart of figure \ref{img:donchian-vs-buyhold}.
The black line indicated the equity curve of the \gls{dcs}, the red one the equity curve of the \gls{bah} strategy.
A couple of things stand out in this chart. First, that the \gls{bah} strategy outperformed the \gls{dcs} in most
years from 1990 on to 2000, when the two equity curves began to move in nearly lockstep to each other.
This began to change in 2006, where the curve for \gls{dcs} began to rise above its counterpart.
It was followed by a period there the two curves again moved almost in lockstep to each other.
However, beginning in about 2015 the \gls{dcs} began to overtake the equity curve of the \gls{bah} strategy
until the end of the observed time period. One further thing to note, is that in late 2018 when the \gla{bah} strategy
declined, it continued to decline until the end of the backtest. But the equity curve of the \gls{dcs} rebounded
after a while and began quickly to rise again.

Also the amount and severity of drawdowns is vastly different for the \gls{dcs} than for the corresponding \gls{bah}
strategy. The lower chart of figure \ref{img:donchian-vs-buyhold} shows, that the \gls{dcs} incurred a larger
and longer drawdown than the \gls{bah} strategy from 1990 to about the middle of the year 2000. Since then, at least
in case of drawdowns the \gls{dcs} fared generally better. The only time, where the \gls{dcs} fared worse, was during
the 2008 financial crisis, which becomes obvious by looking at the chart. Nonetheless, all its later drawdowns were
not as severe than the ones incurred by the \gls{bah} strategy. 

Figure \ref{img:relative-performance} shows the relative performance of both strategy in one chart. When the curve
rises, the \gls{dcs} fared better and vice versa for the \gls{bah} strategy. As already stated above and reinforced
in this figure, the two strategies spent a lot of time trading in tandem to each other. But also, in time the \gls{dcs}
performed better, the outperformance was substantial. This can be seen most clearly by looking at the time period from
2014 until the end of the observed period. In fact, the outperformance gets even more pronounced approaching the end
of 2018. 

	\begin{figure}[H]
		\centering
		\caption{Donchian Channel Strategy vs Buy \& Hold - Equity Curves}
		\label{img:donchian-vs-buyhold}
		\includegraphics[width = 10cm]{strategy_vs_market}
	\end{figure}



	\begin{figure}[H]
		\centering
		\caption{Donchain Channel vs Buy \& Hold: Relative Performance}
		\label{img:relative-performance}
		\includegraphics[width = 10cm]{relative_performance}
	\end{figure}

Table \ref{tab:both-tradestats}, shows the trading statistics of table \ref{img:buyhold-performance} and table \ref{tab:strategy-stats}
in one comprehensive table. Comparing the net trading \gls{pl} of both strategies it becomes evident, that the \gls{dcs}
generated a larger profit that the \gls{bah} strategy. This amounts to a difference of $1085320. 

Also the amount of the maximum drawdown both strategies encountered varied. While the \gls{bah} strategy incurred
a maximum drawdown of -$1704800, the \gls{dcs} strategy on the other hand only incurred a maximum drawdown of
-$1266610. Therefore, also judging by this risk metric the \gls{dcs} can be deemed superior. 

Thus it is not surprising, that the \gls{dcs} strategy also possesses a higher calmar ratio.
While the \gls{bah} strategy only has a ratio of 1.814389, the \gls{dcs} has a ratio of 3.298955 and can therefore
be seen as the superior strategy according to this metric. 

\FloatBarrier
\begin{table}[!htbp] \centering
  \caption{Donchian Channel Strategy vs Buy & Hold - Trade Statistics}
  \label{tab:both-tradestats}
\begin{tabular}{@{\extracolsep{5pt}} ccc}
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & AAPL & AAPL.1 \\
\hline \\[-1.8ex]
Portfolio & donchian-channel & buyHold \\
Symbol & AAPL & AAPL \\
Number of Transactions & 67 & 2 \\
Number of Trades & 33 & 1 \\
Net Trading PL & 4178491 & 3093171 \\
Average Trade PL & 114166.4 & 3093171 \\
Median Trade PL & -2063.58 & 3093171 \\
Largest Winner & 1224190 & 3093171 \\
Largest Loser & -138581.5 & 0 \\
Gross Profits & 4045903 & 3093171 \\
Gross Losses & -278411.5 & 0 \\
Standard Deviation Trade PL & 299234.9 &  \\
Standard Err Trade PL & 52090.11 &  \\
Percent Positive & 42.42424 & 100 \\
Percent Negative & 57.57576 & 0 \\
Profit Factor & 14.53209 &  \\
Average Winning Trade & 288993 & 3093171 \\
Median Winning Trade & 123304.2 & 3093171 \\
Average Losing Trade & -14653.24 &  \\
Median Losing Trade & -6617.14 &  \\
Average Daily PL & 114166.4 & 3093171 \\
Median Daily PL & -2063.58 & 3093171 \\
Standard Deviation Daily PL & 299234.9 &  \\
Standard Err Daily PL & 52090.11 &  \\
Annual Sharpe Ratio & 6.056564 &  \\
Maximum Drawdown & -1266610 & -1704800 \\
Calmar Ratio & 3.298955 & 1.814389 \\
Average WinLoss Ratio & 19.72213 &  \\
Median WinLoss Ratio & 18.63407 &  \\
Maximum Equity & 4873301 & 4609972 \\
Minimum Equity & -81340.76 & -22187.5 \\
End Equity & 4178491 & 3093171 \\
\hline \\[-1.8ex]
\end{tabular}
\end{table}
\FloatBarrier

Since the calmar ratio of the \gls{dcs} is higher than the ratio of the \gls{bah} strategy, one can easily determine
that the \gls{dcs} is the strategy to be favored. But this result can be misleading. As already stated in section
\ref{sec:ff-intro} it is advisable to test if the strategy is dependent on one or more of the factors
Fama and French presented in their paper. If the strategy does not generate any alpha or even a negative alpha
and is dependent on any of these risk factors, the strategy is only successful because it takes on the risks delineated by
these factors. 

Table \ref{tab:regression} shows the output of the regression of the excess returns ($gross\; returns - risk\; free\; rate$ ) against the three Fama-French Factors.
The factor delineated as /MktRf/ in the regression output is the market return adjusted by the risk free rate. This factor shows the \gls{dcs} returns sensitivity to the
markets excess returns.
The factor symbolized by SMB stands for /small minus big/, meaning that stocks with a smaller market capitalization
outperform stocks with a bigger market capitalization. This factor tests if the \gls{dcs} is exposed to this risk.
The last factor in this model tests if the strategy is susceptible to the low book value effect and is delineated by /HL/.
If this factor is found to be significant, the strategy is also exposed to this effect. 

The bottom of the table shows the legend to determine the significance levels based on the p-values of these factors.
It becomes immediately obvious that all factors together are significant by looking at the value for the F Statistic.
The F Statistic exhibits a value of 24.008 and is therefore significant at the 0.01 level.

\FloatBarrier
\begin{table}[!htbp] \centering
  \caption{Fama French 3 Factor Regression}
  \label{tab:regression}
\begin{tabular}{@{\extracolsep{5pt}}lc}
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\
\cline{2-2}
\\[-1.8ex] & excess\_returns \\
\hline \\[-1.8ex]
 MktRf & 0.001$^{***}$ \\
  & (0.0002) \\
  & \\
 SMB & 0.001$^{***}$ \\
  & (0.0004) \\
  & \\
 HL & $-$0.002$^{***}$ \\
  & (0.0004) \\
  & \\
 Constant & $-$0.010$^{***}$ \\
  & (0.0003) \\
  & \\
\hline \\[-1.8ex]
Observations & 7,306 \\
R$^{2}$ & 0.010 \\
Adjusted R$^{2}$ & 0.009 \\
Residual Standard  Error & 0.022 (df = 7302) \\
F Statistic & 24.088$^{***}$ (df = 3; 7302) \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
\FloatBarrier

Also it can be seen that the strategy is susceptible to every individual risk factor shown in this model at a
0.01 significance level. This means that the excess returns of the \gls{dcs} can be explained by these risk factors. 

But more importantly, the strategy does not generate a positive alpha. In fact, is produces a negative alpha of -1%.
This shows, that the strategy is not generating any positive return.

* Conclusion

In the sections above, two trading strategies have been presented. The first one, was the \gls{bah} strategy, which
served as the benchmark against which the quantitative trading strategy was measured. The quantitative trading strategy
chosen in this paper was the \gls{dcs} which generates a long signal after the upper channel of the Donchian Channel
is broken, and a short signal after the lower bound is broken. Both of these strategies were backtested using the
Apple stock in the period from 1990-2028 as an example. It could be seen, that the \gls{dcs} traded more actively than
the \gls{bah} strategy while generating more profit and exhibiting lower risk levels measured by the net profits and
the maximum drawdown respectively. 

But the main measure used to compare these strategies was the *Calmar Ratio*, which takes the net profit and the
maximum drawdown in relation to each other and therefore presents us a value which can be interpreted as the
amount of profit in units of risk.
Again, the \gls{dcs} beat the corresponding \gls{bah} strategy by a wide margin, considering this statistic. 

However, the final test of validity of the superiority of the \gls{dcs} was conducted by  regressing the three Fama-Franch
Risk factors onto the excess returns of the strategy. It could be seen that the strategy was exposed to any of these
three risk factors and even generated a negative alpha. This results shows clearly that the \gls{dcs} is not a
viable strategy, but relies on taking on the aforementioned risks to generate its superior result. 

Nonetheless it is important to note the limitations of this backtest. First, the strategy was only tested on the
Apple stock and therefore it is possible that the strategy does just not fare well on this stock but does so on another
asset.
Another caveat is that the strategy only traded in position sizes of $20000 and did not increase the position size
whenever two or more successive signals in the same market direction have been triggered. This /pyramiding/ of positions
can alter the results dramatically.
Also, the \gls{dcs} is just one of many different quantitative trading strategies in existence, it may very well be
that another strategy might yield a positive result. 

On the other hand, the backtest presented in this paper was done assuming a round trip fee of just $10. This value
was chosen for ease of purpose and may not be very realistic. Choosing a higher value or a value based on a percentage
order size allows for a more realistic estimation of the strategy and will certainly lower its return.  

Further, the backtest in this paper did not take any taxes into account. This is a truly unrealistic assumption which
further skews the returns of the \gls{dcs} to the positive side and makes it seem more viable. 

It could be seen, that the \gls{dcs} did not beat the \gls{bah} strategy and should therefore not be implemented
with real money. Since it could not be proven that it is possible to beat the market, Fama and Frenchs findings, that
the market is efficient, could not be disputed.

#+LaTeX: \begin{appendices}
\newpage

bibliography:references.bib

\newpage
* Appendix
#+NAME: Optimization Script
**  Script for Optimization
\label{sec:opt}
#+BEGIN_SRC R
if (!require("quantstrat")) {
    if(!require("devtools")) {
        install.packages("devtools")
        require(devtools)
    }
    install_github("braverock/blotter") # dependency
    install_github("braverock/quantstrat")
}

install.packages("quantmod")

library(quantstrat)
library(quantmod)


currency("USD")

# set up the financial asset used and the dates

initDate <- "1980-01-01"
startDate <- "1980-01-01"
endDate <- "1989-12-31"

getSymbols("AAPL", from = startDate, to = endDate)#, from = startDate, to = endDate, adjusted = TRUE)
stock("AAPL", currency="USD", multiplier = 1)
AAPL <- na.omit(AAPL)
# Set up initial equity and transaction costs
start_equity <- 1e6
orderSize <- start_equity * 0.02
fee = -10 # Transaction fee of $10
stopp_loss <- 0.02

init_n <- 20
n_opt_range <- 1:100


Sys.setenv(TZ="UTC")


donchian_strategy <- "donchian-channel"

# set up the strategy and portfolio components
rm.strat(donchian_strategy)

strategy(donchian_strategy, store = TRUE)
initPortf(donchian_strategy, "AAPL", initDate = initDate)
initAcct(donchian_strategy,  portfolios = donchian_strategy,
         initDate = initDate, initEq = start_equity,
         currency = 'USD')

initOrders(donchian_strategy, initDate = initDate)

addPosLimit(
    portfolio = donchian_strategy,
    symbol = "AAPL",
    timestamp = initDate,
    maxpos = orderSize)

# Create the indicator
add.indicator(strategy = donchian_strategy,
              name = "DonchianChannel",
              arguments = list(HL = quote(HLC(mktdata)[, 1:2]),
                               n = init_n,
                               include.lag = TRUE
                               ),
              label = "DNC")

#---- Set up the signals ----#
add.signal(donchian_strategy, name = "sigComparison",
           arguments = list(
               columns = c("Close", "high.DNC"),
               relationship = "gt"),
           label = "long" )

add.signal(donchian_strategy, name = "sigComparison",
           arguments = list(
               columns = c("Close", "low.DNC"),
               relationship = "lt"),
           label = "short" )


#---- Set up the Rules ---- #

# Enter Long
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = "long",
             sigval = TRUE,
             orderside = "long",
             ordertype = "market",
             replace = FALSE,
             osFUN = osMaxPos,
             orderqty = +orderSize),
         type = "enter",
         label = "EnterLong",
         )

# Enter short
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = "short",
             sigval = TRUE,
             orderside = "short",
             ordertype = "market",
             osFUN = osMaxPos,
             replace = FALSE,
             orderqty = -orderSize),
         type = "enter",
         label = "EnterShort"
         )


# Exit Long
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = 'short',
             sigval = TRUE,
             orderqty = 'all',
             ordertype = 'market',
             replace = TRUE,
             TxnFees = fee,
             orderside = 'long'),
         type = 'exit'
         )

# Exit Short
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = 'long',
             sigval = TRUE,
             orderqty = 'all',
             ordertype = 'market',
             replace = TRUE,
             TxnFees = fee,
             orderside = 'short'),
         type = 'exit'
         )



# Optimize the parameter

add.distribution(donchian_strategy,
                 paramset.label = 'DonchianChannel',
                 component.type = 'indicator',
                 component.label = 'DNC',
                 variable = list(n = n_opt_range),
                 label = 'days_opt')
library(parallel)
detectCores()

if( Sys.info()['sysname'] == "Windows" )
{
    library(doParallel)
    registerDoParallel(cores=detectCores())
} else {
    library(doMC)
    registerDoMC(cores=detectCores())
}



optimization <- apply.paramset(donchian_strategy,
                               paramset.label='DonchianChannel',
                               portfolio.st=donchian_strategy,
                               account.st=donchian_strategy, nsamples=0)

tradeResults <- optimization$tradeStats
idx <- order(tradeResults[,1], tradeResults[,2])
tradeResults <- tradeResults[idx,]

max_calmar_parameter <- which.max(tradeResults$Profit.To.Max.Draw)
max_calmar_parameter

#+END_SRC


#+NAME: Trading Script
**  Script for Backtesting & Analysis
\label{sec:trading}
#+BEGIN_SRC R
# ----- IMPORTANT -----
# Please set the working directory to the current directory using setwd()
# before running the script


# Setup cpde taken from
if (!require("quantstrat")) {
    if(!require("devtools")) {
        install.packages("devtools")
        require(devtools)
    }
    install_github("braverock/blotter") # dependency
    install_github("braverock/quantstrat")
}

install.packages("lattice")
install.packages("quantmod")
install.packages("xts")
install.packages("stargazer")
install.packages("lubridate")
install.packages("fBasics")

library(quantstrat)
library(lattice)
library(quantmod)
library(xts)
library(stargazer)
library(lubridate)
library(fBasics)
options(scipen=999)

options(repr.plot.width = 6, repr.plot.height = 4)
currency("USD")

# set up the financial asset and the dates

initDate <- "1990-01-01"
startDate <- "1990-01-01"
endDate <- "2018-12-31"

getSymbols("AAPL", from = startDate, to = endDate)
AAPL <- na.omit(AAPL)
colnames(AAPL) <- c('Open', 'High', 'Low', 'Close', 'Volume', 'Adjusted')

# Set up initial equity and transaction costs
start_equity <- 1e6
orderSize <- start_equity * 0.02
fee = -10 # Transaction fee of $2
stopp_loss <- 0.02

options(repr.plot.width = 6, repr.plot.height = 4)
init_n <- 95


Sys.setenv(TZ="UTC")


donchian_strategy <- "donchian-channel"
rm.strat(donchian_strategy)

stock("AAPL", currency="USD", multiplier = 1)
strategy(donchian_strategy, store = TRUE)
initPortf(donchian_strategy, "AAPL")
initAcct(donchian_strategy,  portfolios = donchian_strategy,
         initEq = start_equity,
         currency = 'USD')

initOrders(donchian_strategy)

addPosLimit(
    portfolio = donchian_strategy,
    symbol = "AAPL",
    timestamp = initDate,
    maxpos = orderSize)


                                        # Create the indicator
add.indicator(strategy = donchian_strategy,
              name = "DonchianChannel",
              arguments = list(HL = quote(HLC(mktdata)[, 1:2]),
                               n = init_n,
                               include.lag = TRUE
                               ),
              label = "DNC")

#---- Set up the signals ----#
add.signal(donchian_strategy, name = "sigComparison",
           arguments = list(
               columns = c("Close", "high.DNC"),
               relationship = "gt"),
           label = "long" )

add.signal(donchian_strategy, name = "sigComparison",
           arguments = list(
               columns = c("Close", "low.DNC"),
               relationship = "lt"),
           label = "short" )


#---- Set up the Rules ---- #

# Enter Long
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = "long",
             sigval = TRUE,
             orderside = "long",
             ordertype = "market",
             replace = FALSE,
             osFUN = osMaxPos,
             orderqty = +orderSize),
         type = "enter",
         label = "EnterLong",
         )

# Enter short
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = "short",
             sigval = TRUE,
             orderside = "short",
             ordertype = "market",
             replace = FALSE,
             osFUN = osMaxPos,
             orderqty = -orderSize),
         type = "enter",
         label = "EnterShort"
         )


# Exit Long
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = 'short',
             sigval = TRUE,
             orderqty = 'all',
             ordertype = 'market',
             replace = TRUE,
             TxnFees = fee,
             orderside = 'long'),
         type = 'exit'
         )

# Exit Short
add.rule(donchian_strategy, name = "ruleSignal",
         arguments = list(
             sigcol = 'long',
             sigval = TRUE,
             orderqty = 'all',
             ordertype = 'market',
             replace = TRUE,
             TxnFees = fee,
             orderside = 'short'),
         type = 'exit'
         )

results <- applyStrategy(donchian_strategy, portfolios = donchian_strategy)
getTxns(Portfolio=donchian_strategy, Symbol="AAPL")

updatePortf(donchian_strategy)
updateAcct(donchian_strategy)
updateEndEq(donchian_strategy)
chart.Posn(donchian_strategy, Symbol = 'AAPL', Dates = '2016::')
chart.Posn(donchian_strategy, Symbol = 'AAPL')

trade_stats <- perTradeStats(donchian_strategy,"AAPL")

tstats = t(tradeStats(donchian_strategy, 'AAPL'))
stargazer(tstats)

mk <- mktdata['1990-01-01::2018-12-31']
mk.df <- data.frame(Date=time(mk),coredata(mk))
mk.df

rets <- PortfReturns(donchian_strategy)
rownames(rets) <- NULL
charts.PerformanceSummary(rets, colorset=bluefocus)

######## buy and hold test
#the code for this this part was taken from
# tim trice book of quantstrat
#https://timtrice.github.io/


rm.strat("buyHold")

initPortf("buyHold", symbols = "AAPL", initDate = initDate)
initAcct('buyHold', portfolios = 'buyHold', initDate = initDate,
         initEq = start_equity)

CurrentDate <- time(getTxns(Portfolio = donchian_strategy,
                            Symbol = "AAPL"))[2]
equity = getEndEq("buyHold", CurrentDate)
ClosePrice <- as.numeric(Cl(AAPL[CurrentDate,]))
addTxn("buyHold", Symbol = "AAPL",
       TxnDate = CurrentDate, TxnPrice = ClosePrice,
       TxnQty = orderSize, TxnFees = 0)

LastDate <- last(time(AAPL))
LastPrice <- as.numeric(Cl(AAPL[LastDate,]))
addTxn("buyHold", Symbol = "AAPL",
       TxnDate = LastDate, TxnPrice = LastPrice,
       TxnQty = -orderSize, TxnFees = 0)

updatePortf(Portfolio = "buyHold")
updateAcct(name = "buyHold")
updateEndEq(Account = "buyHold")
chart.Posn("buyHold", Symbol = "AAPL")

tstats_buyhold = t(tradeStats('buyHold', 'AAPL'))
tstats_buyhold
stargazer(tstats_buyhold)


#Performance Summary
returns = PortfReturns(donchian_strategy)
colnames(returns) = 'Dochian Strategy'
charts.PerformanceSummary(returns, colorset = 'darkblue')
return_buyhold <- PortfReturns(Account = "buyHold")
colnames(return_buyhold) = 'Buy and Hold'
charts.PerformanceSummary(return_buyhold, colorset='darkblue')
return_both = cbind(returns, return_buyhold)
charts.PerformanceSummary(return_both, geometric = FALSE,
                           wealth.index = TRUE,
                           main = 'Donchian Channel Strategy vs Market')


buyhold_per_trade_stats <- t(perTradeStats('buyHold',"AAPL"))
buyhold_per_trade_stats

# Total returns over the observed time perios
buyhold_total_return <- (as.numeric(tstats_buyhold[length(tstats_buyhold)]) / start_equity) * 100
buyhold_total_return
strategy_total_return <- (as.numeric(tstats[length(tstats)]) / start_equity) * 100
strategy_total_return

times_market <- as.numeric(tstats[length(tstats)]) / as.numeric(tstats_buyhold[length(tstats_buyhold)])
times_market

#---- Relative Performance -----
chart.RelativePerformance(returns, return_buyhold,
                          colorset = c("red", "blue"), lwd = 2,
                          legend.loc = "topleft")

#---- Fama French 3 Factor Model ----
ff_factors <- read.csv2("ff_factors.csv", sep = ',')

# change the columns to the correct data type
ff_factors$Mkt.RF <- as.numeric(as.character(ff_factors$Mkt.RF))
ff_factors$SMB <- as.numeric(as.character(ff_factors$SMB))
ff_factors$HML <- as.numeric(as.character(ff_factors$HML))
ff_factors$RF <- as.numeric(as.character(ff_factors$RF))

# Convert the first column to a date format
colnames(ff_factors)[1] <- "Date"
ff_factors$Date <-  ymd(ff_factors$Date)
ff_date <- ff_factors$Date
ff_factors <- ff_factors[, -1]

# Rename the columns
# MktRf = Market Return above Risk Free Rate
# SMB = Size Factor
# HL = Book Value/Market Value
# RF = Risk Free Rate
colnames(ff_factors) <- c("MktRf", "SMB", "HL", "RF")

# Create an XTS Object
ff_factors <- xts(ff_factors, ff_date)
ff_factors <- ff_factors["1990/20181228"]
## ff_factors <- ff_factors/100

excess_returns = PortfReturns(donchian_strategy) - ff_factors$RF
# FF 3 Factor Model
model <- lm(excess_returns ~ MktRf + SMB + HL, data=ff_factors)
summary(model)
stargazer(model)

# Portfolio Summary Graphs
strategy_pf <- getPortfolio(donchian_strategy)
xyplot(strategy_pf$summary, type = "h", col = 4)

buyhold_pf <- getPortfolio("buyHold")
xyplot(buyhold_pf$summary, type = "h", col = 4)

# Summary statistics of Buy & Hold strategy
buyhold_summary <- basicStats(return_buyhold * 100)
stargazer(buyhold_summary, digits = c(0, 5))


# Summary statistics of the Donchian Channel strategy
strategy_summary <- basicStats(returns * 100)
stargazer(strategy_summary, digits = c(0, 5))

# Tstats table for both
tstats_table_both <- cbind(tstats, tstats_buyhold)
stargazer(tstats_table_both)

# Chart the whole series
initDate <- "1980-01-01"
startDate <- "1980-01-01"
endDate <- "2018-12-31"

getSymbols("AAPL", from = startDate, to = endDate)
chartSeries(AAPL, subset = '2001::2002', theme="white", TA=NULL )
addSMA(n=10, col = 'red')
addSMA(n=20, col = 'blue')
#+END_SRC

#+RESULTS:

# \printbibliography
